#!/bin/bash
#  ____   _  _____ _   _ 
# |  _ \ / \|_   _| | | |
# | |_) / _ \ | | | |_| |
# |  __/ ___ \| | |  _  |
# |_| /_/   \_\_| |_| |_|
 

# mes svripts
if $_isScripts____; then
  for directory in $dir_scripts___/* ; do
    if [ -d "$directory" ]; then
      PATH="$PATH:$directory"
    fi
  done
  PATH=$PATH:$dir_scripts___
fi

# run arch in termux
$_isArch_______ && PATH=$PATH:$dir_arch______

# run open-url/open file in termux
$_isTermux_____ && PATH=$PATH:$dir_termux____

# apps:python...
$_isLocal______ && PATH=$PATH:$dir_local_____

# java termux
$_isJdk________ && PATH=$PATH:$dir_jdk_______
$_isJli________ && PATH=$PATH:$dir_jli_______

# android sdk
$_isGradle_____ && PATH=$PATH:$dir_gradle____
$_isSDK1_______ && PATH=$PATH:$dir_sdk1______
$_isSDK2_______ && PATH=$PATH:$dir_sdk2______

# gitmux for git in tmux
$_isGitmux_____ && PATH=$PATH:$dir_gitmux____


# remove duplique path
# PATH export with awk
PATH=$(printf "%s" "$PATH" | awk -v RS=':' '!a[$1]++ { if (NR > 1) printf RS; printf $1 }')
 
 
export PATH
