#!/bin/bash
#  ____   _  _____ _   _ 
# |  _ \ / \|_   _| | | |
# | |_) / _ \ | | | |_| |
# |  __/ ___ \| | |  _  |
# |_| /_/   \_\_| |_| |_|



# mes svripts
if [ -e $HOME/scripts ]; then
  for directory in $HOME/scripts/*/* ; do
    if [ -d "$directory" ]; then
      PATH="$PATH:$directory"
    fi
  done
  PATH=$PATH:"$HOME/scripts/my"
fi

# run arch in termux
PATH=$PATH:"$HOME/arch"
# run open-url/open file in termux
PATH=$PATH:"$HOME/bin"

# apps:python...
PATH=$PATH:"$HOME/.local/bin"

# java termux
#PATH=$PATH:"$PREFIX/jdk/bin"
#PATH=$PATH:"$PREFIX/jdk/lib/jli"

# android sdk
# PATH=$PATH:"/opt/sdk/gradle/gradle-7.0.1/bin"
# PATH=$PATH:"/opt/sdk/kotlin-native-linux-1.4.32/bin"
PATH=$PATH:"/opt/sdk/gradle/gradle-6.5/bin"
PATH=$PATH:"/opt/sdk/android/platform-tools"
PATH=$PATH:"/opt/sdk/android/tools/bin"

# gitmux for git in tmux
PATH=$PATH:"$HOME/.config/myConfig/gitmux"


# remove duplique path
# PATH export with awk
PATH=$(printf "%s" "$PATH" | awk -v RS=':' '!a[$1]++ { if (NR > 1) printf RS; printf $1 }')


export PATH
