#!/bin/bash
# _______  ______   ___  ____ _____ 
#| ____\ \/ /  _ \ / _ \|  _ \_   _|
#|  _|  \  /| |_) | | | | |_) || |  
#| |___ /  \|  __/| |_| |  _ < | |  
#|_____/_/\_\_|    \___/|_| \_\|_|  

$_isShare && export XDG_DATA_HOME=$HOME/.local/share
$_isDownload && export DOWNLOAD=$HOME/storage/downloads
$_isAppProject && export AppProjects=$HOME/storage/downloads/AppProjects

# JAVA_HOME
$_isJdk && export JAVA_HOME=$PREFIX/jdk
$_isJli && export LD_LIBRARY_PATH=$PREFIX/jdk/lib/jli


# GRADLE_USER_HOME
$_isGradlec && export GRADLE_USER_HOME=$HOME/android-sdk/gradlec
$_isGradle  && export GRADLE_HOME=$HOME/android-sdk/gradle-6.6.1
# $_isGradlec && export GRADLE_USER_HOME=$HOME/android-sdk/gradlec683
# $_isGradle  && export GRADLE_HOME=$HOME/android-sdk/gradle-6.8.3


# sdk android
$_isAndroidHome && export ANDROID_HOME=$HOME/android-sdk
$_isAndroidHome && export ANDROID_SDK_ROOT=$HOME/android-sdk
$_isAndroidHome && export ANDROID_SDK_HOME=$HOME/android-sdk

