#!/bin/bash
# _______  ______   ___  ____ _____ 
#| ____\ \/ /  _ \ / _ \|  _ \_   _|
#|  _|  \  /| |_) | | | | |_) || |  
#| |___ /  \|  __/| |_| |  _ < | |  
#|_____/_/\_\_|    \___/|_| \_\|_|  

export XDG_DATA_HOME="$HOME/.local/share"
export DOWNLOAD="$HOME/storage/downloads"
export AppProjects="$HOME/storage/downloads/AppProjects"

# JAVA_HOME
export JAVA_HOME=$PREFIX/jdk
export LD_LIBRARY_PATH="$PREFIX/jdk/lib/jli"


# GRADLE_USER_HOME
export GRADLE_USER_HOME="$PREFIX/android-sdk/gradlec"
export GRADLE_HOME="$PREFIX/android-sdk/gradle-6.8.3/bin"


# sdk android
export ANDROID_HOME="$PREFIX/android-sdk"
export ANDROID_SDK_ROOT="$PREFIX/android-sdk"
export ANDROID_SDK_HOME="$PREFIX/android-sdk"
