#!/bin/bash
# _______  ______   ___  ____ _____ 
#| ____\ \/ /  _ \ / _ \|  _ \_   _|
#|  _|  \  /| |_) | | | | |_) || |  
#| |___ /  \|  __/| |_| |  _ < | |  
#|_____/_/\_\_|    \___/|_| \_\|_|  

export XDG_DATA_HOME="$HOME/.local/share"
export DOWNLOAD="$HOME/storage/downloads"
export AppProjects="$HOME/storage/downloads/AppProjects"

# JAVA_HOME
export JAVA_HOME=/usr/lib/jvm/openjdk11-bin


# GRADLE_USER_HOME
export GRADLE_USER_HOME="/opt/sdk/gradlec"
# export GRADLE_HOME="/opt/sdk/gradle/gradle-7.0.1"
export GRADLE_HOME="/opt/sdk/gradle/gradle-6.5"


# sdk android
export ANDROID_HOME="/opt/sdk/android"
export ANDROID_SDK_ROOT="/opt/sdk/android"
export ANDROID_SDK_HOME="/opt/sdk/android-HOME"
