#!/bin/bash
# _______  ______   ___  ____ _____ 
#| ____\ \/ /  _ \ / _ \|  _ \_   _|
#|  _|  \  /| |_) | | | | |_) || |  
#| |___ /  \|  __/| |_| |  _ < | |  
#|_____/_/\_\_|    \___/|_| \_\|_|  

$_isShare______ && export XDG_DATA_HOME=$dir_share_____
$_isDownload___ && export DOWNLOAD=$dir_Download__
$_isAppProject_ && export AppProjects=$dir_appproject

# JAVA_HOME
$_isJdk________ && export JAVA_HOME=$PREFIX/jdk
$_isJli________ && export LD_LIBRARY_PATH=$dir_jli_______


# GRADLE_USER_HOME
$_isGradlec____ && export GRADLE_USER_HOME=$dir_gradlec___
$_isGradle_____ && export GRADLE_HOME=$dir_gradle____


# sdk android
$_isAndroidHome && export ANDROID_HOME=$dir_andro_home
$_isAndroidHome && export ANDROID_SDK_ROOT=$dir_andro_home
$_isAndroidHome && export ANDROID_SDK_HOME=$dir_andro_home

